import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Property, Lead, Deal, Appointment, DashboardMetrics } from '../types';

export const generatePropertyPDF = (property: Property): string => {
  const doc = new jsPDF();

  // Header banner
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, 210, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.text('REALTY PULSE', 14, 22);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text('OFFICIAL PROPERTY DOSSIER & INTELLIGENCE REPORT', 14, 32);

  // Property Overview
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(property.title, 14, 52);

  doc.setFontSize(12);
  doc.setTextColor(37, 99, 235); // primary blue
  doc.text(`Price: ${property.currency} $${property.price.toLocaleString()}`, 14, 60);

  doc.setTextColor(71, 85, 105);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Location: ${property.address}, ${property.city}, ${property.state}`, 14, 67);

  // Specifications Table
  autoTable(doc, {
    startY: 75,
    head: [['Property Attribute', 'Specification Detail']],
    body: [
      ['Property Type', property.property_type.toUpperCase()],
      ['Status', property.status.toUpperCase()],
      ['Bedrooms', String(property.bedrooms)],
      ['Bathrooms', String(property.bathrooms)],
      ['Living Area', `${property.area.toLocaleString()} sq ft`],
      ['Furnishing', property.furnishing],
      ['Amenities', property.amenities.join(', ') || 'N/A'],
      ['Listing Date', new Date(property.listing_date).toLocaleDateString()],
    ],
    theme: 'striped',
    headStyles: { fillColor: [30, 41, 59] },
  });

  // Description
  const finalY = (doc as any).lastAutoTable.finalY || 140;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('Property Description & AI Highlights:', 14, finalY + 12);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85);

  const splitText = doc.splitTextToSize(property.description || 'No description provided.', 180);
  doc.text(splitText, 14, finalY + 20);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(`Generated by RealtyPulse Operating System on ${new Date().toLocaleString()}`, 14, 285);

  doc.save(`${property.title.replace(/[^a-zA-Z0-9]/g, '_')}_Report.pdf`);
  return doc.output('datauristring');
};

export const generateExecutiveReportPDF = (metrics: DashboardMetrics, deals: Deal[], leads: Lead[]): string => {
  const doc = new jsPDF();

  // Header
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 36, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('REALTY PULSE - EXECUTIVE ANALYTICS REPORT', 14, 22);

  // Key KPI Summary
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(14);
  doc.text('Financial & Operational Performance Summary', 14, 48);

  autoTable(doc, {
    startY: 54,
    head: [['Metric', 'Value Record']],
    body: [
      ['Total Closed Revenue', `$${metrics.totalRevenue.toLocaleString()}`],
      ['Total Earned Commission', `$${metrics.totalCommission.toLocaleString()}`],
      ['Total Properties Tracked', String(metrics.totalProperties)],
      ['Active Listings', String(metrics.activeListings)],
      ['Total CRM Leads', String(metrics.totalLeads)],
      ['Qualified Hot Leads', String(metrics.qualifiedLeads)],
      ['Closed Won Deals', String(metrics.closedDeals)],
      ['Lead Conversion Rate', `${metrics.conversionRate.toFixed(1)}%`],
    ],
    theme: 'grid',
    headStyles: { fillColor: [15, 23, 42] },
  });

  // Recent Deals Table
  const dealsY = (doc as any).lastAutoTable.finalY + 12;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Recent Closed & Active Deals', 14, dealsY);

  autoTable(doc, {
    startY: dealsY + 6,
    head: [['Property', 'Value', 'Commission', 'Status', 'Closing Date']],
    body: deals.map(d => [
      d.property_title || d.property_id,
      `$${d.deal_value.toLocaleString()}`,
      `$${d.commission.toLocaleString()}`,
      d.status.toUpperCase(),
      d.closing_date ? new Date(d.closing_date).toLocaleDateString() : 'N/A'
    ]),
    theme: 'striped',
    headStyles: { fillColor: [30, 41, 59] },
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(`Confidential - RealtyPulse Analytics Engine - ${new Date().toLocaleDateString()}`, 14, 285);

  doc.save(`RealtyPulse_Executive_Report_${Date.now()}.pdf`);
  return doc.output('datauristring');
};
